"""Made all foreign keys cascade ondelete

Revision ID: 0de613ff16b6
Revises: 9e1bc913ce93
Create Date: 2026-09-04 21:43:02.236949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de613ff16b6'
down_revision = '9e1bc913ce93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('flashcards_learning_word_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'learning_words', ['learning_word_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('learning_words', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('learning_words_word_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('learning_words_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'words', ['word_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sentences_learning_word_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'learning_words', ['learning_word_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transcript_lines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transcript_lines_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_videos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_videos_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_videos_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('word_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_forms_word_id'), ['word_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('word_forms_word_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'words', ['word_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_forms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('word_forms_word_id_fkey'), 'words', ['word_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_word_forms_word_id'))

    with op.batch_alter_table('user_videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_videos_video_id_fkey'), 'videos', ['video_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_videos_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('transcript_lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transcript_lines_video_id_fkey'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sentences_learning_word_id_fkey'), 'learning_words', ['learning_word_id'], ['id'])

    with op.batch_alter_table('learning_words', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('learning_words_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('learning_words_word_id_fkey'), 'words', ['word_id'], ['id'])

    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('flashcards_learning_word_id_fkey'), 'learning_words', ['learning_word_id'], ['id'])

    # ### end Alembic commands ###
