"""Renamed user_videos table to plural form

Revision ID: 9e1bc913ce93
Revises: 
Create Date: 2026-07-18 01:21:29.352476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1bc913ce93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_video', 'user_videos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_videos', 'user_video')
    # ### end Alembic commands ###
